### ISSUE TITLE
Startup Crash with Canary and Hopper+ on 1.18.2, Forge 40.2.0

### ISSUE THREAD

**Issue by xFirefalconx** [AbdElAziz333/Canary#122]
### Version
canary-mc1.18.2-0.1.6.jar

also important to know: 
hplus-1.18.2-3.3.1-forge.jar

### Reproduction Steps

1. install canary and the mod "hopper+" on a 1.18.2 Forge 40.2.0 modpack. 
2. start the game
3. the game will crash and not output any crash logs
4. navigate to latest logs and it says something concerning "hopper+". 

### Crash Report File

There is no crash log written, at least I got none. The latest.log though shows about what happened, as well. Let me know if you need more info, I'll happily provide them as far as I can. 
[latest.log](https://github.com/AbdElAziz333/Canary/files/11184232/latest.log)

### Minecraft Save
N/A

### Additional Information

Upon reading about the issue on Hopper+, it also happened to the mod lithium. I though don't know if it's a different issue that causes the crash. Might be interesting to see what Lithium did to solve the issue, though. 

"Master64
Posted Dec 14, 2022
[#317](https://www.curseforge.com/minecraft/mc-mods/hopper?comment=317)

Just so you know, this mod (on 1.18.2) seems to now have an incompatibility with Lithium, causing a crash on startup due to something related to the minecart hopper.

Edit: Problem on Lithium's end, sorry! Just a configuration option.
Last edited by [Master64](https://www.curseforge.com/members/master64): Dec 14, 2022"

**Comment by AbdElAziz333** [comment]
it should be fixed in the new updates, i hope you have a good day!

**Comment by xFirefalconx** [comment]
Hi, thanks for the reply. Which version are you referring to? 
I still experience the crash on canary-mc1.18.2-0.2.3.

In case something unforseen happened, let me attach the logs again:
My modpack:
[latest.log](https://github.com/AbdElAziz333/Canary/files/11782768/latest.log)

Flytre, Hopper+ and Canary:
[latest.log](https://github.com/AbdElAziz333/Canary/files/11782777/latest.log)

No crash reports were generated, but these might help figure out what happened. Somebody else replied to me on the Flytre Discord, apparently they have the same problem.

**Comment by AbdElAziz333** [comment]
You can add mixin.entity.hopper_minecraft=false in Canary config file until I release a fix for this bug.

**Comment by xFirefalconx** [comment]
I tried to do so but even that makes the game crash. Are you sure hopperPlus hoppers are included in this mixin? I feel like there's a difference between them and vanilla hoppers. 
[latest.log](https://github.com/AbdElAziz333/Canary/files/11793518/latest.log)

I double-checked whether the config was saved correctly, but yes it was so I doubt I did a mistake. 
Looking forward to your answers. Let me know if you need any more info.
