### ISSUE TITLE
re-open plz | Hopper+ /Canary startup crash without Crash-Report(Exit Code 1). 1.18.2 Forge 40.2.17

### ISSUE THREAD

**Issue by xFirefalconx** [AbdElAziz333/Canary#133]
### Version
Minecraft 1.18.2
Forge 40.2.0
hplus-1.18.2-3.3.1-forge.jar
canary-mc1.18.2-0.1.7.jar

### Reproduction Steps
Add Canary and Hopper+ (Better Hoppers) to a 1.18.2 modpack and press play. 

### Crash Report File

No crash report generated. I had the debug log running though and used a mod (unrelated to the issue) to generate more info on the crash. 
[latest.log](https://github.com/AbdElAziz333/Canary/files/11444856/latest.log)

### Minecraft Save
N/A can't open game.

### Additional Information
Somebody on the Fabric side had this issue as well, they mentioned something like configuration issue on Lithium. I have no clue whether I can do anything concerning this. I just see both mods (Hopper+ and Canary) sometimes get compatibility and crash fix updates.

**Comment by AbdElAziz333** [comment]
should be fixed in the latest update.

**Comment by xFirefalconx** [comment]
Re-opening, (sorry for delay I was very busy)
Still crashing because of mixin conflict (according to Blue Corgi, who took a look at my log)
I still have the file with 

```
mixin.entity.hopper_minecraft=false
```
under canary.properties
as written above, that doesn't seem to address the issue. Maybe it's a modded emulation of the hopper or the sort that bypasses that mixin rule? The mod is adding a new sort of hopper, if I understand correctly. Or the deactivation is not working, I am just assuming. 

Current mod version: 1.18.2-0.3.2
Forge 40.2.17

Log: 
[hplus_canary_crash_latest.log](https://github.com/AbdElAziz333/Canary/files/14116555/hplus_canary_crash_latest.log)

Please take a look, I hope you know what is wrong here 🙈 Will deactivate hplus until the next test cycle in hope we'll get them compatible some day.
