### ISSUE TITLE
Canary prevents Immersive Engineering from showing graphic multiblock building instructions.

### ISSUE THREAD

**Issue by bangtothepow940** [AbdElAziz333/Canary#72]
### Version Information

Canary 0.0.10 for 1.18.2

### Expected Behavior

The first page of any multiblock machine in the engineer's manual shows an animation on how to build the structure step-by-step.

### Actual Behavior

The first page of any multiblock machine in the engineer's manual doesn't show said animation.

### Reproduction Steps

1. Install both Canary and Immersive Engineering.
2. Get the Engineer's Manual.
3. Open any page about any multiblock machine (Arc furnace or Sawmill for example)
4. There is supposed to be an animation on the top of the page, but it doesn't show. Leaving the top of the page blank.

### Other Information

An example of what Engineer's manual looks like without Canary :

https://i.imgur.com/GLKMKQB.png

With canary, it looks the same expect there isn't the multiblock structure showing.

**Comment by CrisperEye6** [comment]
Having the same issue with Canary 0.1.0 for MC 1.18.2

**Comment by malte0811** [comment]
I can't test with Canary right now, but I'm quite sure it's the same issue that was reported with Radium last week or so. It's fixed in IE in https://github.com/BluSunrize/ImmersiveEngineering/commit/bc1ffa842c5c6d411a487d88870b70165c524377.

**Comment by AbdElAziz333** [comment]
this issue is fixed in the old Canary versions, but i made a lot changes so maybe it back, but you fixed it in your side so sounds is so good.
Thanks for fixing the issue in your side.
I hope you have a good day!

**Comment by Proxwian** [comment]
No, that’s not fixed, still persist with latest IE and Canary versions installed.

**Comment by Proxwian** [comment]
Why are you closing without asking or testing at least..

**Comment by AbdElAziz333** [comment]
I tested it and it still happens i know, malte fixed it in Immersive Engineering's coming update, that's the reason why i closed this issue.
