### ISSUE TITLE
Canary 0.1.4 Breaks Nether Portal Link Again

### ISSUE THREAD

**Issue by stop-x13** [AbdElAziz333/Canary#98]
could you please test the new version?
[1.19.3](https://www.curseforge.com/minecraft/mc-mods/canary/files/4307894) - [1.19.2](https://www.curseforge.com/minecraft/mc-mods/canary/files/4307893) - [1.18.2](https://www.curseforge.com/minecraft/mc-mods/canary/files/4307891).

_Originally posted by @AbdElAziz333 in https://github.com/AbdElAziz333/Canary/issues/85#issuecomment-1373503221_

This issue is related to 0.1.4 for 1.18.2.
Have not tested 0.1.3 yet, but on 0.1.4 when I try to enter nether from overworld, I cannot exit on nether roof anymore (which is possible in vanilla, and earlier version of Canary).

Edit:
I tested 0.1.0 as well, didn't work for nether portal on nether ceiling.
I had amplified nether installed and raised the build limit to 379 in the nether, but it did worked before.

**Comment by AbdElAziz333** [comment]
can you test the latest update?, if the issue fixed in the new update please close the issue.

**Comment by stop-x13** [comment]
Checked latest update, still failed to teleport to portal above bedrock.

**Comment by Sephiroth91** [comment]
With Canary 0.1.6 the portal link is broken and every portal leaving a new portal is creating in overworld. If I use in the canary config mixin.ai.poi.fast_portals=false  no new portal is creating.

**Comment by AbdElAziz333** [comment]
can you please use the new update?
[1.19.4](https://legacy.curseforge.com/minecraft/mc-mods/canary/files/4498538) - [1.19.3](https://legacy.curseforge.com/minecraft/mc-mods/canary/files/4498537) - [1.19.2](https://legacy.curseforge.com/minecraft/mc-mods/canary/files/4498536) - [1.18.2](https://legacy.curseforge.com/minecraft/mc-mods/canary/files/4498539)
